run:
  tests: true

linters:
  enable:
    - revive
    - ireturn

issues:
  exclude-dirs:
    - apigen
  exclude-rules:
    - linters:
        - revive
      source: ". \"github.com/onsi/(ginkgo/v2|gomega)\""
      text: "dot-imports: should not use dot imports"

linters-settings:
  revive:
    enable-all-rules: false
    ignore-generated-header: false
    severity: error
    confidence: 0.8
    rules:
      - name: argument-limit
        arguments: [3]
      - name: blank-imports
      - name: cognitive-complexity
        arguments: [7]
        exclude:
          - "TEST"
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: errorf
      - name: exported
      - name: function-result-limit
        arguments: [3]
      - name: import-shadowing
      - name: increment-decrement
      - name: indent-error-flow
      - name: max-control-nesting
        arguments: [3]
      - name: modifies-parameter
      - name: package-comments
        severity: warning
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: struct-tag
      - name: superfluous-else
      - name: time-equal
      - name: time-naming
      - name: unexported-return
      - name: unhandled-error
      - name: unreachable-code
      - name: unused-parameter
      - name: use-any
      - name: var-declaration
      - name: var-naming
