// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// WailsLog is an autogenerated mock type for the WailsLog type
type WailsLog struct {
	mock.Mock
}

type WailsLog_Expecter struct {
	mock *mock.Mock
}

func (_m *WailsLog) EXPECT() *WailsLog_Expecter {
	return &WailsLog_Expecter{mock: &_m.Mock}
}

// LogDebug provides a mock function with given fields: ctx, message
func (_m *WailsLog) LogDebug(ctx context.Context, message string) {
	_m.Called(ctx, message)
}

// WailsLog_LogDebug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogDebug'
type WailsLog_LogDebug_Call struct {
	*mock.Call
}

// LogDebug is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
func (_e *WailsLog_Expecter) LogDebug(ctx interface{}, message interface{}) *WailsLog_LogDebug_Call {
	return &WailsLog_LogDebug_Call{Call: _e.mock.On("LogDebug", ctx, message)}
}

func (_c *WailsLog_LogDebug_Call) Run(run func(ctx context.Context, message string)) *WailsLog_LogDebug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WailsLog_LogDebug_Call) Return() *WailsLog_LogDebug_Call {
	_c.Call.Return()
	return _c
}

func (_c *WailsLog_LogDebug_Call) RunAndReturn(run func(context.Context, string)) *WailsLog_LogDebug_Call {
	_c.Call.Return(run)
	return _c
}

// LogDebugf provides a mock function with given fields: ctx, format, args
func (_m *WailsLog) LogDebugf(ctx context.Context, format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// WailsLog_LogDebugf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogDebugf'
type WailsLog_LogDebugf_Call struct {
	*mock.Call
}

// LogDebugf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...interface{}
func (_e *WailsLog_Expecter) LogDebugf(ctx interface{}, format interface{}, args ...interface{}) *WailsLog_LogDebugf_Call {
	return &WailsLog_LogDebugf_Call{Call: _e.mock.On("LogDebugf",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *WailsLog_LogDebugf_Call) Run(run func(ctx context.Context, format string, args ...interface{})) *WailsLog_LogDebugf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *WailsLog_LogDebugf_Call) Return() *WailsLog_LogDebugf_Call {
	_c.Call.Return()
	return _c
}

func (_c *WailsLog_LogDebugf_Call) RunAndReturn(run func(context.Context, string, ...interface{})) *WailsLog_LogDebugf_Call {
	_c.Call.Return(run)
	return _c
}

// LogError provides a mock function with given fields: ctx, message
func (_m *WailsLog) LogError(ctx context.Context, message string) {
	_m.Called(ctx, message)
}

// WailsLog_LogError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogError'
type WailsLog_LogError_Call struct {
	*mock.Call
}

// LogError is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
func (_e *WailsLog_Expecter) LogError(ctx interface{}, message interface{}) *WailsLog_LogError_Call {
	return &WailsLog_LogError_Call{Call: _e.mock.On("LogError", ctx, message)}
}

func (_c *WailsLog_LogError_Call) Run(run func(ctx context.Context, message string)) *WailsLog_LogError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WailsLog_LogError_Call) Return() *WailsLog_LogError_Call {
	_c.Call.Return()
	return _c
}

func (_c *WailsLog_LogError_Call) RunAndReturn(run func(context.Context, string)) *WailsLog_LogError_Call {
	_c.Call.Return(run)
	return _c
}

// LogErrorf provides a mock function with given fields: ctx, format, args
func (_m *WailsLog) LogErrorf(ctx context.Context, format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// WailsLog_LogErrorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogErrorf'
type WailsLog_LogErrorf_Call struct {
	*mock.Call
}

// LogErrorf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...interface{}
func (_e *WailsLog_Expecter) LogErrorf(ctx interface{}, format interface{}, args ...interface{}) *WailsLog_LogErrorf_Call {
	return &WailsLog_LogErrorf_Call{Call: _e.mock.On("LogErrorf",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *WailsLog_LogErrorf_Call) Run(run func(ctx context.Context, format string, args ...interface{})) *WailsLog_LogErrorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *WailsLog_LogErrorf_Call) Return() *WailsLog_LogErrorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *WailsLog_LogErrorf_Call) RunAndReturn(run func(context.Context, string, ...interface{})) *WailsLog_LogErrorf_Call {
	_c.Call.Return(run)
	return _c
}

// LogFatal provides a mock function with given fields: ctx, message
func (_m *WailsLog) LogFatal(ctx context.Context, message string) {
	_m.Called(ctx, message)
}

// WailsLog_LogFatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogFatal'
type WailsLog_LogFatal_Call struct {
	*mock.Call
}

// LogFatal is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
func (_e *WailsLog_Expecter) LogFatal(ctx interface{}, message interface{}) *WailsLog_LogFatal_Call {
	return &WailsLog_LogFatal_Call{Call: _e.mock.On("LogFatal", ctx, message)}
}

func (_c *WailsLog_LogFatal_Call) Run(run func(ctx context.Context, message string)) *WailsLog_LogFatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WailsLog_LogFatal_Call) Return() *WailsLog_LogFatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *WailsLog_LogFatal_Call) RunAndReturn(run func(context.Context, string)) *WailsLog_LogFatal_Call {
	_c.Call.Return(run)
	return _c
}

// LogFatalf provides a mock function with given fields: ctx, format, args
func (_m *WailsLog) LogFatalf(ctx context.Context, format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// WailsLog_LogFatalf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogFatalf'
type WailsLog_LogFatalf_Call struct {
	*mock.Call
}

// LogFatalf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...interface{}
func (_e *WailsLog_Expecter) LogFatalf(ctx interface{}, format interface{}, args ...interface{}) *WailsLog_LogFatalf_Call {
	return &WailsLog_LogFatalf_Call{Call: _e.mock.On("LogFatalf",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *WailsLog_LogFatalf_Call) Run(run func(ctx context.Context, format string, args ...interface{})) *WailsLog_LogFatalf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *WailsLog_LogFatalf_Call) Return() *WailsLog_LogFatalf_Call {
	_c.Call.Return()
	return _c
}

func (_c *WailsLog_LogFatalf_Call) RunAndReturn(run func(context.Context, string, ...interface{})) *WailsLog_LogFatalf_Call {
	_c.Call.Return(run)
	return _c
}

// LogInfo provides a mock function with given fields: ctx, message
func (_m *WailsLog) LogInfo(ctx context.Context, message string) {
	_m.Called(ctx, message)
}

// WailsLog_LogInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogInfo'
type WailsLog_LogInfo_Call struct {
	*mock.Call
}

// LogInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
func (_e *WailsLog_Expecter) LogInfo(ctx interface{}, message interface{}) *WailsLog_LogInfo_Call {
	return &WailsLog_LogInfo_Call{Call: _e.mock.On("LogInfo", ctx, message)}
}

func (_c *WailsLog_LogInfo_Call) Run(run func(ctx context.Context, message string)) *WailsLog_LogInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WailsLog_LogInfo_Call) Return() *WailsLog_LogInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *WailsLog_LogInfo_Call) RunAndReturn(run func(context.Context, string)) *WailsLog_LogInfo_Call {
	_c.Call.Return(run)
	return _c
}

// LogInfof provides a mock function with given fields: ctx, format, args
func (_m *WailsLog) LogInfof(ctx context.Context, format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// WailsLog_LogInfof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogInfof'
type WailsLog_LogInfof_Call struct {
	*mock.Call
}

// LogInfof is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...interface{}
func (_e *WailsLog_Expecter) LogInfof(ctx interface{}, format interface{}, args ...interface{}) *WailsLog_LogInfof_Call {
	return &WailsLog_LogInfof_Call{Call: _e.mock.On("LogInfof",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *WailsLog_LogInfof_Call) Run(run func(ctx context.Context, format string, args ...interface{})) *WailsLog_LogInfof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *WailsLog_LogInfof_Call) Return() *WailsLog_LogInfof_Call {
	_c.Call.Return()
	return _c
}

func (_c *WailsLog_LogInfof_Call) RunAndReturn(run func(context.Context, string, ...interface{})) *WailsLog_LogInfof_Call {
	_c.Call.Return(run)
	return _c
}

// LogPrint provides a mock function with given fields: ctx, message
func (_m *WailsLog) LogPrint(ctx context.Context, message string) {
	_m.Called(ctx, message)
}

// WailsLog_LogPrint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogPrint'
type WailsLog_LogPrint_Call struct {
	*mock.Call
}

// LogPrint is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
func (_e *WailsLog_Expecter) LogPrint(ctx interface{}, message interface{}) *WailsLog_LogPrint_Call {
	return &WailsLog_LogPrint_Call{Call: _e.mock.On("LogPrint", ctx, message)}
}

func (_c *WailsLog_LogPrint_Call) Run(run func(ctx context.Context, message string)) *WailsLog_LogPrint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WailsLog_LogPrint_Call) Return() *WailsLog_LogPrint_Call {
	_c.Call.Return()
	return _c
}

func (_c *WailsLog_LogPrint_Call) RunAndReturn(run func(context.Context, string)) *WailsLog_LogPrint_Call {
	_c.Call.Return(run)
	return _c
}

// LogPrintf provides a mock function with given fields: ctx, format, args
func (_m *WailsLog) LogPrintf(ctx context.Context, format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// WailsLog_LogPrintf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogPrintf'
type WailsLog_LogPrintf_Call struct {
	*mock.Call
}

// LogPrintf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...interface{}
func (_e *WailsLog_Expecter) LogPrintf(ctx interface{}, format interface{}, args ...interface{}) *WailsLog_LogPrintf_Call {
	return &WailsLog_LogPrintf_Call{Call: _e.mock.On("LogPrintf",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *WailsLog_LogPrintf_Call) Run(run func(ctx context.Context, format string, args ...interface{})) *WailsLog_LogPrintf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *WailsLog_LogPrintf_Call) Return() *WailsLog_LogPrintf_Call {
	_c.Call.Return()
	return _c
}

func (_c *WailsLog_LogPrintf_Call) RunAndReturn(run func(context.Context, string, ...interface{})) *WailsLog_LogPrintf_Call {
	_c.Call.Return(run)
	return _c
}

// LogTrace provides a mock function with given fields: ctx, message
func (_m *WailsLog) LogTrace(ctx context.Context, message string) {
	_m.Called(ctx, message)
}

// WailsLog_LogTrace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogTrace'
type WailsLog_LogTrace_Call struct {
	*mock.Call
}

// LogTrace is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
func (_e *WailsLog_Expecter) LogTrace(ctx interface{}, message interface{}) *WailsLog_LogTrace_Call {
	return &WailsLog_LogTrace_Call{Call: _e.mock.On("LogTrace", ctx, message)}
}

func (_c *WailsLog_LogTrace_Call) Run(run func(ctx context.Context, message string)) *WailsLog_LogTrace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WailsLog_LogTrace_Call) Return() *WailsLog_LogTrace_Call {
	_c.Call.Return()
	return _c
}

func (_c *WailsLog_LogTrace_Call) RunAndReturn(run func(context.Context, string)) *WailsLog_LogTrace_Call {
	_c.Call.Return(run)
	return _c
}

// LogTracef provides a mock function with given fields: ctx, format, args
func (_m *WailsLog) LogTracef(ctx context.Context, format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// WailsLog_LogTracef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogTracef'
type WailsLog_LogTracef_Call struct {
	*mock.Call
}

// LogTracef is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...interface{}
func (_e *WailsLog_Expecter) LogTracef(ctx interface{}, format interface{}, args ...interface{}) *WailsLog_LogTracef_Call {
	return &WailsLog_LogTracef_Call{Call: _e.mock.On("LogTracef",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *WailsLog_LogTracef_Call) Run(run func(ctx context.Context, format string, args ...interface{})) *WailsLog_LogTracef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *WailsLog_LogTracef_Call) Return() *WailsLog_LogTracef_Call {
	_c.Call.Return()
	return _c
}

func (_c *WailsLog_LogTracef_Call) RunAndReturn(run func(context.Context, string, ...interface{})) *WailsLog_LogTracef_Call {
	_c.Call.Return(run)
	return _c
}

// LogWarning provides a mock function with given fields: ctx, message
func (_m *WailsLog) LogWarning(ctx context.Context, message string) {
	_m.Called(ctx, message)
}

// WailsLog_LogWarning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogWarning'
type WailsLog_LogWarning_Call struct {
	*mock.Call
}

// LogWarning is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
func (_e *WailsLog_Expecter) LogWarning(ctx interface{}, message interface{}) *WailsLog_LogWarning_Call {
	return &WailsLog_LogWarning_Call{Call: _e.mock.On("LogWarning", ctx, message)}
}

func (_c *WailsLog_LogWarning_Call) Run(run func(ctx context.Context, message string)) *WailsLog_LogWarning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WailsLog_LogWarning_Call) Return() *WailsLog_LogWarning_Call {
	_c.Call.Return()
	return _c
}

func (_c *WailsLog_LogWarning_Call) RunAndReturn(run func(context.Context, string)) *WailsLog_LogWarning_Call {
	_c.Call.Return(run)
	return _c
}

// LogWarningf provides a mock function with given fields: ctx, format, args
func (_m *WailsLog) LogWarningf(ctx context.Context, format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// WailsLog_LogWarningf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogWarningf'
type WailsLog_LogWarningf_Call struct {
	*mock.Call
}

// LogWarningf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...interface{}
func (_e *WailsLog_Expecter) LogWarningf(ctx interface{}, format interface{}, args ...interface{}) *WailsLog_LogWarningf_Call {
	return &WailsLog_LogWarningf_Call{Call: _e.mock.On("LogWarningf",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *WailsLog_LogWarningf_Call) Run(run func(ctx context.Context, format string, args ...interface{})) *WailsLog_LogWarningf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *WailsLog_LogWarningf_Call) Return() *WailsLog_LogWarningf_Call {
	_c.Call.Return()
	return _c
}

func (_c *WailsLog_LogWarningf_Call) RunAndReturn(run func(context.Context, string, ...interface{})) *WailsLog_LogWarningf_Call {
	_c.Call.Return(run)
	return _c
}

// NewWailsLog creates a new instance of WailsLog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWailsLog(t interface {
	mock.TestingT
	Cleanup(func())
}) *WailsLog {
	mock := &WailsLog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
