// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CoinTrackingBackend is an autogenerated mock type for the CoinTrackingBackend type
type CoinTrackingBackend struct {
	mock.Mock
}

type CoinTrackingBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *CoinTrackingBackend) EXPECT() *CoinTrackingBackend_Expecter {
	return &CoinTrackingBackend_Expecter{mock: &_m.Mock}
}

// OpenExportFile provides a mock function with given fields: timezone
func (_m *CoinTrackingBackend) OpenExportFile(timezone string) (string, error) {
	ret := _m.Called(timezone)

	if len(ret) == 0 {
		panic("no return value specified for OpenExportFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(timezone)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(timezone)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(timezone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoinTrackingBackend_OpenExportFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenExportFile'
type CoinTrackingBackend_OpenExportFile_Call struct {
	*mock.Call
}

// OpenExportFile is a helper method to define mock.On call
//   - timezone string
func (_e *CoinTrackingBackend_Expecter) OpenExportFile(timezone interface{}) *CoinTrackingBackend_OpenExportFile_Call {
	return &CoinTrackingBackend_OpenExportFile_Call{Call: _e.mock.On("OpenExportFile", timezone)}
}

func (_c *CoinTrackingBackend_OpenExportFile_Call) Run(run func(timezone string)) *CoinTrackingBackend_OpenExportFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CoinTrackingBackend_OpenExportFile_Call) Return(_a0 string, _a1 error) *CoinTrackingBackend_OpenExportFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoinTrackingBackend_OpenExportFile_Call) RunAndReturn(run func(string) (string, error)) *CoinTrackingBackend_OpenExportFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewCoinTrackingBackend creates a new instance of CoinTrackingBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoinTrackingBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoinTrackingBackend {
	mock := &CoinTrackingBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
