// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BlockpitBackend is an autogenerated mock type for the BlockpitBackend type
type BlockpitBackend struct {
	mock.Mock
}

type BlockpitBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *BlockpitBackend) EXPECT() *BlockpitBackend_Expecter {
	return &BlockpitBackend_Expecter{mock: &_m.Mock}
}

// ExportToBlockpitXlsx provides a mock function with given fields:
func (_m *BlockpitBackend) ExportToBlockpitXlsx() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExportToBlockpitXlsx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BlockpitBackend_ExportToBlockpitXlsx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportToBlockpitXlsx'
type BlockpitBackend_ExportToBlockpitXlsx_Call struct {
	*mock.Call
}

// ExportToBlockpitXlsx is a helper method to define mock.On call
func (_e *BlockpitBackend_Expecter) ExportToBlockpitXlsx() *BlockpitBackend_ExportToBlockpitXlsx_Call {
	return &BlockpitBackend_ExportToBlockpitXlsx_Call{Call: _e.mock.On("ExportToBlockpitXlsx")}
}

func (_c *BlockpitBackend_ExportToBlockpitXlsx_Call) Run(run func()) *BlockpitBackend_ExportToBlockpitXlsx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BlockpitBackend_ExportToBlockpitXlsx_Call) Return(_a0 error) *BlockpitBackend_ExportToBlockpitXlsx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BlockpitBackend_ExportToBlockpitXlsx_Call) RunAndReturn(run func() error) *BlockpitBackend_ExportToBlockpitXlsx_Call {
	_c.Call.Return(run)
	return _c
}

// NewBlockpitBackend creates a new instance of BlockpitBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockpitBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockpitBackend {
	mock := &BlockpitBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
