// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	common "github.com/tomvodi/cointracking-export-converter/internal/common"

	mock "github.com/stretchr/testify/mock"
)

// XmlWriter is an autogenerated mock type for the XmlWriter type
type XmlWriter struct {
	mock.Mock
}

type XmlWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *XmlWriter) EXPECT() *XmlWriter_Expecter {
	return &XmlWriter_Expecter{mock: &_m.Mock}
}

// WriteTransactionsToXmlFile provides a mock function with given fields: filePath, transactions
func (_m *XmlWriter) WriteTransactionsToXmlFile(filePath string, transactions []*common.CointrackingTx) error {
	ret := _m.Called(filePath, transactions)

	if len(ret) == 0 {
		panic("no return value specified for WriteTransactionsToXmlFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []*common.CointrackingTx) error); ok {
		r0 = rf(filePath, transactions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// XmlWriter_WriteTransactionsToXmlFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteTransactionsToXmlFile'
type XmlWriter_WriteTransactionsToXmlFile_Call struct {
	*mock.Call
}

// WriteTransactionsToXmlFile is a helper method to define mock.On call
//   - filePath string
//   - transactions []*common.CointrackingTx
func (_e *XmlWriter_Expecter) WriteTransactionsToXmlFile(filePath interface{}, transactions interface{}) *XmlWriter_WriteTransactionsToXmlFile_Call {
	return &XmlWriter_WriteTransactionsToXmlFile_Call{Call: _e.mock.On("WriteTransactionsToXmlFile", filePath, transactions)}
}

func (_c *XmlWriter_WriteTransactionsToXmlFile_Call) Run(run func(filePath string, transactions []*common.CointrackingTx)) *XmlWriter_WriteTransactionsToXmlFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]*common.CointrackingTx))
	})
	return _c
}

func (_c *XmlWriter_WriteTransactionsToXmlFile_Call) Return(_a0 error) *XmlWriter_WriteTransactionsToXmlFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *XmlWriter_WriteTransactionsToXmlFile_Call) RunAndReturn(run func(string, []*common.CointrackingTx) error) *XmlWriter_WriteTransactionsToXmlFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewXmlWriter creates a new instance of XmlWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewXmlWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *XmlWriter {
	mock := &XmlWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
