// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function GetExportFiles():Promise<Array<common.ExportFileInfo>>;

export function OpenExportFile(arg1:string):Promise<string>;
