// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetExportFiles() {
  return window['go']['cointracking']['Backend']['GetExportFiles']();
}

export function OpenExportFile(arg1) {
  return window['go']['cointracking']['Backend']['OpenExportFile'](arg1);
}
