// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function BlockpitTxTypes():Promise<Array<common.TxDisplayName>>;

export function OpenExportFile(arg1:string):Promise<string>;

export function TxTypeMappings():Promise<Array<common.Ct2BpTxMapping>>;
