// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockpitTxTypes() {
  return window['go']['cointracking']['ct']['BlockpitTxTypes']();
}

export function ExportToBlockpitXlsx() {
  return window['go']['cointracking']['ct']['ExportToBlockpitXlsx']();
}

export function GetExportFiles() {
  return window['go']['cointracking']['ct']['GetExportFiles']();
}

export function OpenExportFile(arg1) {
  return window['go']['cointracking']['ct']['OpenExportFile'](arg1);
}

export function SetCointracking2BlockpitMapping(arg1, arg2) {
  return window['go']['cointracking']['ct']['SetCointracking2BlockpitMapping'](arg1, arg2);
}

export function TxTypeMappings() {
  return window['go']['cointracking']['ct']['TxTypeMappings']();
}
