// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllTimezones() {
  return window['go']['config']['appConfig']['AllTimezones']();
}

export function BlockpitTxTypes() {
  return window['go']['config']['appConfig']['BlockpitTxTypes']();
}

export function SetCointracking2BlockpitMapping(arg1, arg2) {
  return window['go']['config']['appConfig']['SetCointracking2BlockpitMapping'](arg1, arg2);
}

export function SetTimezone(arg1) {
  return window['go']['config']['appConfig']['SetTimezone'](arg1);
}

export function Timezone() {
  return window['go']['config']['appConfig']['Timezone']();
}

export function TxTypeMappings() {
  return window['go']['config']['appConfig']['TxTypeMappings']();
}
