// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllTimezones() {
  return window['go']['config']['appConfig']['AllTimezones']();
}

export function SetTimezone(arg1) {
  return window['go']['config']['appConfig']['SetTimezone'](arg1);
}

export function Timezone() {
  return window['go']['config']['appConfig']['Timezone']();
}
