// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllTimezones() {
  return window['go']['config']['AppConfig']['AllTimezones']();
}

export function BlockpitTxTypes() {
  return window['go']['config']['AppConfig']['BlockpitTxTypes']();
}

export function SetCointracking2BlockpitMapping(arg1, arg2) {
  return window['go']['config']['AppConfig']['SetCointracking2BlockpitMapping'](arg1, arg2);
}

export function SetSwapHandling(arg1) {
  return window['go']['config']['AppConfig']['SetSwapHandling'](arg1);
}

export function SetTimezone(arg1) {
  return window['go']['config']['AppConfig']['SetTimezone'](arg1);
}

export function SwapHandling() {
  return window['go']['config']['AppConfig']['SwapHandling']();
}

export function Timezone() {
  return window['go']['config']['AppConfig']['Timezone']();
}

export function TxTypeMappings() {
  return window['go']['config']['AppConfig']['TxTypeMappings']();
}
