// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Init():Promise<void>;

export function SetTimezone(arg1:string):Promise<void>;

export function Timezone():Promise<string>;
