// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTimezoneLocation():Promise<string>;

export function SetTimezoneLocation(arg1:string):Promise<void>;
