// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTimezoneLocation() {
  return window['go']['app']['App']['GetTimezoneLocation']();
}

export function SetTimezoneLocation(arg1) {
  return window['go']['app']['App']['SetTimezoneLocation'](arg1);
}
