package common

import (
	bp "cointracking-export-converter/internal/common/blockpit_tx_type"
	ct "cointracking-export-converter/internal/common/cointracking_tx_type"
)

var Ct2BpMap = map[ct.CtTxType]bp.BpTxType{
	ct.NoCtTxType:               bp.NoBpTxType,
	ct.Trade:                    bp.Trade,
	ct.MarginTrade:              bp.Trade,
	ct.DerivativesFuturesTrade:  bp.Trade,
	ct.Deposit:                  bp.Deposit,
	ct.Income:                   bp.Income,
	ct.GiftTip:                  bp.GiftReceived,
	ct.RewardBonus:              bp.Bounty,
	ct.Mining:                   bp.Mining,
	ct.Airdrop:                  bp.Airdrop,
	ct.AirdropNonTaxable:        bp.NonTaxableIn,
	ct.Staking:                  bp.Staking,
	ct.Masternode:               bp.Masternode,
	ct.Minting:                  bp.Trade,
	ct.MiningCommercial:         bp.Mining,
	ct.DividendsIncome:          bp.Income,
	ct.LendingIncome:            bp.Income,
	ct.InterestIncome:           bp.Income,
	ct.DerivativesFuturesProfit: bp.Income,
	ct.MarginProfit:             bp.Income,
	ct.OtherIncome:              bp.Income,
	ct.IncomeNonTaxable:         bp.NonTaxableIn,
	ct.RemoveLiquidity:          bp.NonTaxableIn,
	ct.ReceiveLpToken:           bp.NonTaxableIn,
	ct.LpRewards:                bp.Income,
	ct.Withdrawal:               bp.Withdrawal,
	ct.Spend:                    bp.GiftSent,
	ct.Donation:                 bp.GiftSent,
	ct.Gift:                     bp.GiftSent,
	ct.Stolen:                   bp.Lost,
	ct.Lost:                     bp.Lost,
	ct.BorrowingFee:             bp.Fee,
	ct.SettlementFee:            bp.Fee,
	ct.MarginLoss:               bp.Lost,
	ct.MarginFee:                bp.Fee,
	ct.DerivativesFuturesLoss:   bp.Lost,
	ct.OtherFee:                 bp.Fee,
	ct.OtherExpense:             bp.Payment,
	ct.ProvideLiquidity:         bp.NonTaxableOut,
	ct.ReturnLpToken:            bp.NonTaxableOut,
	ct.ExpenseNonTaxable:        bp.NonTaxableOut,
	ct.SwapNonTaxable:           bp.NonTaxableOut,
	ct.ReceiveLoan:              bp.NonTaxableIn,
	ct.ReceiveCollateral:        bp.NonTaxableIn,
	ct.SendCollateral:           bp.NonTaxableOut,
	ct.RepayLoan:                bp.Payment,
	ct.Liquidation:              bp.Trade,
}
